import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class StudentDatabaseTest {

    Student underTest;
    StudentDatabase stuBase;
    Course course;

    @BeforeEach
    void setUp() {
        underTest = new Student("noah", "doughty");
        stuBase = new StudentDatabase();
        course = new Course();
    }

    @Test
    void canCreateNewStudent() {
        underTest.addNewStudent();
    }

    @Test
    void canAddCourses() {
        course.addNewCourse();
        assertThat("History 102").isEqualTo("History101");
    }

    @Test
    void canCreateAutoGeneratedPassword() {

    }

    @Test
    void studentShouldBeAbleToSeeTuitionBalance() {
        //Student underTest
        //Collection of courses
        // studentDatabase.calculateBalance();

    }

}
//assertThat("string").equals("string")); T or F statement

//assertThat(int[] array).contains(elementAdded)); Whatever creates a boolean value


//